<?php

namespace Database\Seeders;

use App\Models\Equipment;
use Illuminate\Database\Seeder;

class RestaurantEquipmentGoogleSheetSeeder extends Seeder
{
    public function run(): void
    {
        $equipmentData = [
            [
                "name" => "Sajji Counter",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-001",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #1).",
            ],
            [
                "name" => "Buffer Inner",
                "quantity" => 15,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-002",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 37500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #2).",
            ],
            [
                "name" => "Dish Buffa",
                "quantity" => 15,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-003",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 37500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #3).",
            ],
            [
                "name" => "Gool Parat",
                "quantity" => 27,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-004",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 67500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #4).",
            ],
            [
                "name" => "Buffa lamp",
                "quantity" => 9,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-005",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 22500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #5).",
            ],
            [
                "name" => "Wooden Table",
                "quantity" => 9,
                "category" => "dining_furniture",
                "serial_number" => "ND-EQ-006",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 22500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #6).",
            ],
            [
                "name" => "Sink double khanna",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-007",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #7).",
            ],
            [
                "name" => "Steel jug",
                "quantity" => 12,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-008",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 30000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #8).",
            ],
            [
                "name" => "Gool Tray",
                "quantity" => 6,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-009",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 15000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #9).",
            ],
            [
                "name" => "Bary Pateely with Dhakkan",
                "quantity" => 6,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-010",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 15000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #10).",
            ],
            [
                "name" => "Choota Pateela",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-011",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #11).",
            ],
            [
                "name" => "Steel pateela",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-012",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #12).",
            ],
            [
                "name" => "Chai cattal steel drammi",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-013",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #13).",
            ],
            [
                "name" => "Pressure Cooker",
                "quantity" => 3,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-014",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 7500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #14).",
            ],
            [
                "name" => "Fry Pan",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-015",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #15).",
            ],
            [
                "name" => "Sauce Pan",
                "quantity" => 3,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-016",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 7500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #16).",
            ],
            [
                "name" => "Channana Rice",
                "quantity" => 4,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-017",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 10000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #17).",
            ],
            [
                "name" => "Sanni Lohy wali",
                "quantity" => 2,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-018",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 5000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #18).",
            ],
            [
                "name" => "Khurpi",
                "quantity" => 2,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-019",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 5000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #19).",
            ],
            [
                "name" => "Steel bowl big",
                "quantity" => 13,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-020",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 32500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #20).",
            ],
            [
                "name" => "Steel bowl choota",
                "quantity" => 14,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-021",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 35000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #21).",
            ],
            [
                "name" => "Bda chulha",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-022",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #22).",
            ],
            [
                "name" => "Kitchen Chulha (6 burner set)",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-023",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #23).",
            ],
            [
                "name" => "Rice Spoon",
                "quantity" => 149,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-024",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 372500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #24).",
            ],
            [
                "name" => "Baby spoon",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-025",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #25).",
            ],
            [
                "name" => "Service spoon",
                "quantity" => 53,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-026",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 132500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #26).",
            ],
            [
                "name" => "Fork kanta",
                "quantity" => 116,
                "category" => "pos_it",
                "serial_number" => "ND-EQ-027",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 290000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #27).",
            ],
            [
                "name" => "Table Knife",
                "quantity" => 80,
                "category" => "dining_furniture",
                "serial_number" => "ND-EQ-028",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 200000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #28).",
            ],
            [
                "name" => "Pizza lifter",
                "quantity" => 25,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-029",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 62500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #29).",
            ],
            [
                "name" => "Tong",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-030",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #30).",
            ],
            [
                "name" => "Buffa chamach",
                "quantity" => 13,
                "category" => "cooling_heating",
                "serial_number" => "ND-EQ-031",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 32500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #31).",
            ],
            [
                "name" => "Ice Cream skooper",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-032",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #32).",
            ],
            [
                "name" => "Knife",
                "quantity" => 9,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-033",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 22500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #33).",
            ],
            [
                "name" => "Chai pawwa",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-034",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #34).",
            ],
            [
                "name" => "Rice Chamach",
                "quantity" => 4,
                "category" => "cooling_heating",
                "serial_number" => "ND-EQ-035",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 10000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #35).",
            ],
            [
                "name" => "Tooka",
                "quantity" => 3,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-036",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 7500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #36).",
            ],
            [
                "name" => "Gripper Pan",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-037",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #37).",
            ],
            [
                "name" => "Gripper Plass",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-038",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #38).",
            ],
            [
                "name" => "Dool Steel big",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-039",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #39).",
            ],
            [
                "name" => "Dool Steel Small",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-040",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #40).",
            ],
            [
                "name" => "Pateeli choti",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-041",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #41).",
            ],
            [
                "name" => "Mitti kanali big",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-042",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #42).",
            ],
            [
                "name" => "Mitti kanali small",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-043",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #43).",
            ],
            [
                "name" => "Plastic Balti",
                "quantity" => 2,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-044",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 5000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #44).",
            ],
            [
                "name" => "Plastic Baliti full size",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-045",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #45).",
            ],
            [
                "name" => "Big rack",
                "quantity" => 1,
                "category" => "cooling_heating",
                "serial_number" => "ND-EQ-046",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #46).",
            ],
            [
                "name" => "fries jali",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-047",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #47).",
            ],
            [
                "name" => "LCD",
                "quantity" => 2,
                "category" => "pos_it",
                "serial_number" => "ND-EQ-048",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 5000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #48).",
            ],
            [
                "name" => "wooden table white first floor",
                "quantity" => 1,
                "category" => "dining_furniture",
                "serial_number" => "ND-EQ-049",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #49).",
            ],
            [
                "name" => "Plastic Dabba masaly waly",
                "quantity" => 7,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-050",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 17500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #50).",
            ],
            [
                "name" => "Sarya grill stand",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-051",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #51).",
            ],
            [
                "name" => "Karahi loha kundday wali",
                "quantity" => 3,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-052",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 7500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #52).",
            ],
            [
                "name" => "Bar B Q phatti with counter",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-053",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #53).",
            ],
            [
                "name" => "Burger showrma counter",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-054",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #54).",
            ],
            [
                "name" => "Kabab sikh",
                "quantity" => 28,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-055",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 70000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #55).",
            ],
            [
                "name" => "Tikka sikh",
                "quantity" => 100,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-056",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 250000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #56).",
            ],
            [
                "name" => "Sajji siikh",
                "quantity" => 11,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-057",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 27500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #57).",
            ],
            [
                "name" => "Bar B Q stand steel",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-058",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #58).",
            ],
            [
                "name" => "Hot Plat bar b q",
                "quantity" => 14,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-059",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 35000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #59).",
            ],
            [
                "name" => "Karahi bdi",
                "quantity" => 28,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-060",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 70000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #60).",
            ],
            [
                "name" => "Karahi choti",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-061",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #61).",
            ],
            [
                "name" => "Karahi full size",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-062",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #62).",
            ],
            [
                "name" => "Fry channna",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-063",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #63).",
            ],
            [
                "name" => "Tub steel / cup",
                "quantity" => 2,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-064",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 5000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #64).",
            ],
            [
                "name" => "Balti steel",
                "quantity" => 2,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-065",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 5000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #65).",
            ],
            [
                "name" => "Magga steel",
                "quantity" => 2,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-066",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 5000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #66).",
            ],
            [
                "name" => "Kundi danda",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-067",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #67).",
            ],
            [
                "name" => "Plastic tokri gool",
                "quantity" => 2,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-068",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 5000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #68).",
            ],
            [
                "name" => "Table steel 3 step",
                "quantity" => 1,
                "category" => "dining_furniture",
                "serial_number" => "ND-EQ-069",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #69).",
            ],
            [
                "name" => "Keema matchine",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-070",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #70).",
            ],
            [
                "name" => "Cheez Crucher matchine",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-071",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #71).",
            ],
            [
                "name" => "Steel chulha bda",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-072",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #72).",
            ],
            [
                "name" => "Drum",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-073",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #73).",
            ],
            [
                "name" => "Pizza pan bda",
                "quantity" => 20,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-074",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 50000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #74).",
            ],
            [
                "name" => "Pizza pan chota",
                "quantity" => 8,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-075",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 20000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #75).",
            ],
            [
                "name" => "Pizza pan midiam",
                "quantity" => 12,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-076",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 30000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #76).",
            ],
            [
                "name" => "Ice cream cup",
                "quantity" => 22,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-077",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 55000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #77).",
            ],
            [
                "name" => "Glass",
                "quantity" => 50,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-078",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 125000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #78).",
            ],
            [
                "name" => "Rack glass",
                "quantity" => 2,
                "category" => "cooling_heating",
                "serial_number" => "ND-EQ-079",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 5000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #79).",
            ],
            [
                "name" => "Tandoor seekh",
                "quantity" => 2,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-080",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 5000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #80).",
            ],
            [
                "name" => "Tandoor belna",
                "quantity" => 2,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-081",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 5000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #81).",
            ],
            [
                "name" => "Nan Thappa",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-082",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #82).",
            ],
            [
                "name" => "Steel backery try",
                "quantity" => 2,
                "category" => "cooling_heating",
                "serial_number" => "ND-EQ-083",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 5000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #83).",
            ],
            [
                "name" => "Steel try choti",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-084",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #84).",
            ],
            [
                "name" => "Gtrander with jug",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-085",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #85).",
            ],
            [
                "name" => "Rice platter big",
                "quantity" => 30,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-086",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 75000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #86).",
            ],
            [
                "name" => "Dinner plate",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-087",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #87).",
            ],
            [
                "name" => "Choti plate",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-088",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #88).",
            ],
            [
                "name" => "Burger try",
                "quantity" => 19,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-089",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 47500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #89).",
            ],
            [
                "name" => "Silver try bdy",
                "quantity" => 2,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-090",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 5000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #90).",
            ],
            [
                "name" => "Tandoor pipe set",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-091",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #91).",
            ],
            [
                "name" => "Small midiam lasani",
                "quantity" => 24,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-092",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 60000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #92).",
            ],
            [
                "name" => "Lasani bdi pizza",
                "quantity" => 6,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-093",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 15000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #93).",
            ],
            [
                "name" => "Rita bowl",
                "quantity" => 64,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-094",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 160000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #94).",
            ],
            [
                "name" => "iron stand yellow",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-095",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #95).",
            ],
            [
                "name" => "partition",
                "quantity" => 2,
                "category" => "dining_furniture",
                "serial_number" => "ND-EQ-096",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 5000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #96).",
            ],
            [
                "name" => "tables  first floor",
                "quantity" => 9,
                "category" => "dining_furniture",
                "serial_number" => "ND-EQ-097",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 22500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #97).",
            ],
            [
                "name" => "Soup bowl bdy",
                "quantity" => 28,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-098",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 70000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #98).",
            ],
            [
                "name" => "Scale kanta",
                "quantity" => 1,
                "category" => "pos_it",
                "serial_number" => "ND-EQ-099",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #99).",
            ],
            [
                "name" => "Table hall wooden",
                "quantity" => 10,
                "category" => "dining_furniture",
                "serial_number" => "ND-EQ-100",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 25000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #100).",
            ],
            [
                "name" => "Chairs wooden",
                "quantity" => 40,
                "category" => "dining_furniture",
                "serial_number" => "ND-EQ-101",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 100000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #101).",
            ],
            [
                "name" => "Owan pizza",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-102",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #102).",
            ],
            [
                "name" => "Frayer",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-103",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #103).",
            ],
            [
                "name" => "Computer syatem",
                "quantity" => 1,
                "category" => "pos_it",
                "serial_number" => "ND-EQ-104",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #104).",
            ],
            [
                "name" => "Breading table",
                "quantity" => 1,
                "category" => "dining_furniture",
                "serial_number" => "ND-EQ-105",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #105).",
            ],
            [
                "name" => "Ac",
                "quantity" => 2,
                "category" => "cooling_heating",
                "serial_number" => "ND-EQ-106",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 5000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #106).",
            ],
            [
                "name" => "Chiller",
                "quantity" => 2,
                "category" => "cooling_heating",
                "serial_number" => "ND-EQ-107",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 5000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #107).",
            ],
            [
                "name" => "Diwan sofa",
                "quantity" => 2,
                "category" => "dining_furniture",
                "serial_number" => "ND-EQ-108",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 5000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #108).",
            ],
            [
                "name" => "Counter big",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-109",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #109).",
            ],
            [
                "name" => "Counter small",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-110",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #110).",
            ],
            [
                "name" => "Deep Freezer big",
                "quantity" => 3,
                "category" => "cooling_heating",
                "serial_number" => "ND-EQ-111",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 7500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #111).",
            ],
            [
                "name" => "VG cooler",
                "quantity" => 2,
                "category" => "cooling_heating",
                "serial_number" => "ND-EQ-112",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 5000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #112).",
            ],
            [
                "name" => "Mobile tandoor",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-113",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #113).",
            ],
            [
                "name" => "Masala set table",
                "quantity" => 1,
                "category" => "dining_furniture",
                "serial_number" => "ND-EQ-114",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #114).",
            ],
            [
                "name" => "Chair white plastic",
                "quantity" => 13,
                "category" => "dining_furniture",
                "serial_number" => "ND-EQ-115",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 32500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #115).",
            ],
            [
                "name" => "Table white plastic",
                "quantity" => 3,
                "category" => "dining_furniture",
                "serial_number" => "ND-EQ-116",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 7500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #116).",
            ],
            [
                "name" => "Big blower duckt",
                "quantity" => 2,
                "category" => "cooling_heating",
                "serial_number" => "ND-EQ-117",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 5000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #117).",
            ],
            [
                "name" => "Bracket fan",
                "quantity" => 4,
                "category" => "cooling_heating",
                "serial_number" => "ND-EQ-118",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 10000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #118).",
            ],
            [
                "name" => "Padistal fans",
                "quantity" => 4,
                "category" => "cooling_heating",
                "serial_number" => "ND-EQ-119",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 10000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #119).",
            ],
            [
                "name" => "Solar betry",
                "quantity" => 4,
                "category" => "lighting_electrical",
                "serial_number" => "ND-EQ-120",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 10000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #120).",
            ],
            [
                "name" => "invetr",
                "quantity" => 2,
                "category" => "lighting_electrical",
                "serial_number" => "ND-EQ-121",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 5000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #121).",
            ],
            [
                "name" => "Con matchine",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-122",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #122).",
            ],
            [
                "name" => "Soalar system plates",
                "quantity" => 38,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-123",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 95000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #123).",
            ],
            [
                "name" => "Sighn board frame",
                "quantity" => 11,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-124",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 27500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #124).",
            ],
            [
                "name" => "3D sign board",
                "quantity" => 1,
                "category" => "lighting_electrical",
                "serial_number" => "ND-EQ-125",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #125).",
            ],
            [
                "name" => "Chair plastic grey",
                "quantity" => 23,
                "category" => "dining_furniture",
                "serial_number" => "ND-EQ-126",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 57500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #126).",
            ],
            [
                "name" => "Table plastic",
                "quantity" => 5,
                "category" => "dining_furniture",
                "serial_number" => "ND-EQ-127",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 12500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #127).",
            ],
            [
                "name" => "Sheesha table",
                "quantity" => 1,
                "category" => "dining_furniture",
                "serial_number" => "ND-EQ-128",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #128).",
            ],
            [
                "name" => "Parking stand knopi",
                "quantity" => 1,
                "category" => "other",
                "serial_number" => "ND-EQ-129",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #129).",
            ],
            [
                "name" => "jumping jhola",
                "quantity" => 1,
                "category" => "other",
                "serial_number" => "ND-EQ-130",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #130).",
            ],
            [
                "name" => "Jholy",
                "quantity" => 3,
                "category" => "other",
                "serial_number" => "ND-EQ-131",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 7500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #131).",
            ],
            [
                "name" => "Nonstick",
                "quantity" => 3,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-132",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 7500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #132).",
            ],
            [
                "name" => "Bowls",
                "quantity" => 35,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-133",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 87500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #133).",
            ],
            [
                "name" => "steel Handi",
                "quantity" => 12,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-134",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 30000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #134).",
            ],
            [
                "name" => "crucher machine masala",
                "quantity" => 1,
                "category" => "cooling_heating",
                "serial_number" => "ND-EQ-135",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #135).",
            ],
            [
                "name" => "Mutton table wooden",
                "quantity" => 1,
                "category" => "dining_furniture",
                "serial_number" => "ND-EQ-136",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #136).",
            ],
            [
                "name" => "delivery bag",
                "quantity" => 3,
                "category" => "other",
                "serial_number" => "ND-EQ-137",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 7500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #137).",
            ],
            [
                "name" => "printer",
                "quantity" => 2,
                "category" => "pos_it",
                "serial_number" => "ND-EQ-138",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 5000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #138).",
            ],
            [
                "name" => "buffer set",
                "quantity" => 1,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-139",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #139).",
            ],
            [
                "name" => "mobile android",
                "quantity" => 1,
                "category" => "pos_it",
                "serial_number" => "ND-EQ-140",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 2500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #140).",
            ],
            [
                "name" => "stimer",
                "quantity" => 2,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-141",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 5000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #141).",
            ],
            [
                "name" => "countainer",
                "quantity" => 4,
                "category" => "kitchen_appliances",
                "serial_number" => "ND-EQ-142",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 10000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #142).",
            ],
            [
                "name" => "bracket fan white 3 in store",
                "quantity" => 3,
                "category" => "cooling_heating",
                "serial_number" => "ND-EQ-143",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 7500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #143).",
            ],
            [
                "name" => "Artificial plant",
                "quantity" => 13,
                "category" => "other",
                "serial_number" => "ND-EQ-144",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 32500,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #144).",
            ],
            [
                "name" => "chairs first floor",
                "quantity" => 36,
                "category" => "dining_furniture",
                "serial_number" => "ND-EQ-145",
                "purchase_date" => "2025-06-01",
                "purchase_cost" => 90000,
                "functional_status" => "operational",
                "notes" => "Imported from Okara Restaurant Master Equipment Registry (Item #145).",
            ],
        ];

        foreach ($equipmentData as $data) {
            Equipment::updateOrCreate(
                ["serial_number" => $data["serial_number"]],
                $data
            );
        }
    }
}
